server:
  port: 8080
  shutdown: graceful

logging:
  config: classpath:log4j2.yml

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  r2dbc:
    url: 'r2dbc:h2:mem:///testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    username: sa
    password:
  sql:
    init:
      mode: always

webclient:
  config:
    max-in-memory-size: 1024
    max-connections: 1000
    pending-acquire-timeout: 0
    pending-acquire-max-count: -1
    max-idle-time: 5000
    max-life-time: 15000
    response-timeout: 10000
    connect-read-timeout: 10000
    connect-write-timeout: 10000
    connect-channel-option-timeout: 3000