DROP TABLE IF EXISTS rank;
CREATE TABLE rank
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type         VARCHAR(50) NOT NULL,
    member        VARCHAR(1000) NOT NULL,
    score        BIGINT NOT NULL DEFAULT 0,
    created_at       DATETIME NOT NULL DEFAULT now(),
    modified_at DATETIME NOT NULL DEFAULT now(),
    CONSTRAINT pk_rank_01 PRIMARY KEY (id)
);